name: Gradle Build & Test
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: ./gradlew clean build --info
