name: Gradle Build & Test
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew clean build --info
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
          files: ./file_service/build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
          verbose: true
